/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.thicuoiki;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;


/**
 *
 * @author PCH107_SV
 */
public class SinhVien extends javax.swing.JFrame {
    DefaultTableModel a=new DefaultTableModel();
    List <Fmain> list=new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SinhVien.class.getName());

    /**
     * Creates new form SinhVien
     */
    public SinhVien() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Bang = new javax.swing.JTable();
        masv = new javax.swing.JLabel();
        hoten = new javax.swing.JLabel();
        masv_txt = new javax.swing.JTextField();
        ht_txt = new javax.swing.JTextField();
        them_txt = new javax.swing.JButton();
        xoa_txt = new javax.swing.JButton();
        sua_txt = new javax.swing.JButton();
        thoat_txt = new javax.swing.JButton();
        MH = new javax.swing.JLabel();
        MH_txt = new javax.swing.JTextField();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setText("Danh Sách Sinh Viên");

        Bang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Số Sinh Viên", "Họ Tên", "Môn Học"
            }
        ));
        jScrollPane1.setViewportView(Bang);

        masv.setText("MaSV:");

        hoten.setText("Họ Tên:");

        masv_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masv_txtActionPerformed(evt);
            }
        });

        them_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        them_txt.setText("Thêm");
        them_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them_txtActionPerformed(evt);
            }
        });

        xoa_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        xoa_txt.setText("Xoá");
        xoa_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoa_txtActionPerformed(evt);
            }
        });

        sua_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sua_txt.setText("Sửa");
        sua_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sua_txtActionPerformed(evt);
            }
        });

        thoat_txt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        thoat_txt.setText("Thoát");

        MH.setText("Môn học");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(masv, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hoten)
                                            .addComponent(MH))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(masv_txt)
                                            .addComponent(ht_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                            .addComponent(MH_txt)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(them_txt)
                                        .addGap(18, 18, 18)
                                        .addComponent(xoa_txt)
                                        .addGap(18, 18, 18)
                                        .addComponent(sua_txt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(thoat_txt)))))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masv)
                    .addComponent(masv_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(hoten))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ht_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MH)
                    .addComponent(MH_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(them_txt)
                    .addComponent(xoa_txt)
                    .addComponent(sua_txt)
                    .addComponent(thoat_txt))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masv_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masv_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masv_txtActionPerformed

    private void them_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_txtActionPerformed
    String maSV = masv_txt.getText();
    String hoTen = ht_txt.getText();
    String MonHoc = MH_txt.getText();

    if (maSV.isEmpty() || hoTen.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ Mã SV và Họ Tên.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) Bang.getModel();
    model.insertRow(0, new Object[]{maSV, hoTen,MonHoc ,"", ""});
    masv_txt.setText("");
    ht_txt.setText("");
    MH_txt.setText("");
    masv_txt.requestFocus();
    }//GEN-LAST:event_them_txtActionPerformed

    private void xoa_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoa_txtActionPerformed
int selectedRow = Bang.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần xoá.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xoá dòng này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        DefaultTableModel model = (DefaultTableModel) Bang.getModel();
        model.removeRow(selectedRow);
    }
    }//GEN-LAST:event_xoa_txtActionPerformed

    private void sua_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sua_txtActionPerformed
int selectedRow = Bang.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để sửa.");
        return;
    }

    String maSV = masv_txt.getText();
    String hoTen = ht_txt.getText();
    String monHoc = MH_txt.getText();

    if (maSV.isEmpty() || hoTen.isEmpty() || monHoc.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.");
        return;
    }
    DefaultTableModel model = (DefaultTableModel) Bang.getModel();
    model.setValueAt(maSV, selectedRow, 0); 
    model.setValueAt(hoTen, selectedRow, 1);
    model.setValueAt(monHoc, selectedRow, 2);

    JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
    }//GEN-LAST:event_sua_txtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SinhVien().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Bang;
    private javax.swing.JLabel MH;
    private javax.swing.JTextField MH_txt;
    private javax.swing.JLabel hoten;
    private javax.swing.JTextField ht_txt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel masv;
    private javax.swing.JTextField masv_txt;
    private javax.swing.JButton sua_txt;
    private javax.swing.JButton them_txt;
    private javax.swing.JButton thoat_txt;
    private javax.swing.JButton xoa_txt;
    // End of variables declaration//GEN-END:variables
}
